default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV.fetch("DB_USERNAME") { `whoami`.strip } %>

development:
  <<: *default
  database: quis_dev

test:
  <<: *default
  database: quis_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
